name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todo dia à meia-noite
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v3
        with:
          github_user_name: jmurja
          outputs: |
            ./output/pacman-contribution-graph.svg
            ./output/pacman-contribution-graph-dark.svg
      - name: Commit and push if needed
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m "update pacman contribution graph" || echo "No changes to commit"
          git push
